services:
  german-db:
    image: postgres:14
    container_name: german-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: german
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  german-backend:
    build: ./backend
    container_name: german-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://german-db:5432/german
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - german-db

  german-frontend:
    build: ./frontend
    container_name: german-frontend
    ports:
      - "3000:80"
    depends_on:
      - german-backend
volumes:
  postgres_data:
