spring.application.name=backend

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/german
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# Application properties
server.port=8080