spring.application.name=backend

# Database configuration
spring.datasource.url=${DATASOURCE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Application properties
server.port=8080