name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execution permissions for Gradle Wrapper
        run: chmod +x ./backend/gradlew # Указываем путь к gradlew

      - name: Build project
        working-directory: ./backend
        run: ./gradlew build -x test # Указываем путь к gradlew

      - name: Build Docker image
        run: docker build -t s25992/german-backend:latest .

      - name: Push Docker image to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push s25992/german-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 37.46.16.152 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@37.46.16.152 <<EOF
          docker pull s25992/german-backend:latest
          cd /root/german
          docker-compose down
          docker-compose up -d
          EOF
